pipeline {
    agent any

    stages {
        stage("Building"){
            steps {
                echo "Building SourceCode"
                sh 'dotnet run --project=MyWebApp'
                echo "Built Successfully"
            }
        }
    }
}