pipeline {
    agent any

    environment {
        sln = '/home/ubuntu/DEVOPS_DOTNET/MyWebApp/Program.cs'
    }

    stages {
        stage("Building"){
            steps {
                echo "Building SourceCode"
                sh 'dotnetBuild %sln%'
                echo "Built Successfully"
            }
        }
    }
}